crafted_and_connected/social/urls.py
# social urls
from django.urls import path
from .views import add_post, load_subcategories, post_detail, like_post, add_comment, notifications, \
    mark_notification_as_read, clear_notifications, follow_user, unfollow_user

urlpatterns = [
    path('add_post/', add_post, name='add_post'),
    path('ajax/load_subcategories/', load_subcategories, name='load_subcategories'),
    path('<int:post_id>/', post_detail, name='post_detail'),
    path('<int:post_id>/like/', like_post, name='like_post'),
    path('<int:post_id>/comment/', add_comment, name='add_comment'),
    path('notifications/', notifications, name='notifications'),
    path('notifications/mark-as-read/<int:notification_id>/', mark_notification_as_read,
         name='mark_notification_as_read'),
    path('clear_notifications/', clear_notifications, name='clear_notifications'),
    path('follow/<int:user_id>/', follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', unfollow_user, name='unfollow_user'),
]

crafted_and_connected/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crafted_and_connected.store.urls')),
    path('accounts/', include('crafted_and_connected.authentication.urls')),
    path('post/', include('crafted_and_connected.social.urls')),
    path('chat/', include('crafted_and_connected.messaging.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crafted_and_connected/social/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following_set', on_delete=models.CASCADE)
    followed = models.ForeignKey(User, related_name='followers_set', on_delete=models.CASCADE)


class Post(models.Model):
    CATEGORY_CHOICES = [
        ('paper', _('Изделия от хартия')),
        ('wax', _('Изделия от восък')),
        ('wood', _('Изделия от дърво')),
        ('ceramics', _('Керамични изделия')),
        ('tapestry', _('Гоблени')),
        ('paintings', _('Картини')),
        ('jewelry', _('Бижута')),
        ('knitting', _('Плетива')),
        ('other', _('Други')),
    ]

    SUBCATEGORY_CHOICES = {
        'paper': [
            ('cards', _('Картички')),
            ('decorations', _('Декорации')),
            ('quilling', _('Квилинг')),
            ('other', _('Други')),
        ],
        'wax': [
            ('candles', _('Свещи')),
            ('other', _('Други')),
        ],
        'wood': [
            ('decorations', _('Декорации')),
            ('tables_and_chairs', _('Маси и столове')),
            ('frames', _('Рамки')),
            ('other', _('Други')),
        ],
        'ceramics': [
            ('cups', _('Чаши')),
            ('plates', _('Чинии')),
            ('decorations', _('Декорации')),
            ('other', _('Други')),
        ],
        'tapestry': [
            ('finished', _('Готови')),
            ('patterns', _('Схеми')),
            ('stamped', _('Щампирани')),
            ('other', _('Други')),
        ],
        'paintings': [
            ('portrait', _('Портретна живопис')),
            ('landscape', _('Пейзажна живопис')),
            ('still_life', _('Натюрморт')),
            ('abstract', _('Абстрактна живопис')),
            ('historical', _('Исторически живопис')),
            ('religious', _('Религиозна живопис')),
            ('allegory', _('Алегория')),
            ('other', _('Други')),
        ],
        'jewelry': [
            ('earrings', _('Обеци')),
            ('necklaces', _('Колиета')),
            ('bracelets', _('Гривни')),
            ('other', _('Други')),
        ],
        'knitting': [
            ('clothes', _('Дрехи')),
            ('toys', _('Играчки')),
            ('accessories', _('Аксесоари')),
            ('decorations', _('Декорации')),
            ('other', _('Други')),
        ],
        'other': []
    }

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_time = models.PositiveIntegerField()  # Number of days
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    subcategory = models.CharField(max_length=50)
    photos = models.ImageField(upload_to='post_photos/')
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def save(self, *args, **kwargs):
        if self.category not in self.SUBCATEGORY_CHOICES or \
                self.subcategory not in dict(self.SUBCATEGORY_CHOICES[self.category]).keys():
            raise ValueError('Invalid subcategory for the selected category.')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_category_display(self):
        return dict(self.CATEGORY_CHOICES).get(self.category)

    def get_subcategory_display(self):
        subcategories = dict(self.SUBCATEGORY_CHOICES.get(self.category, []))
        return subcategories.get(self.subcategory)


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Нов коментар от {self.user} на {self.post.title}'


class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='post_likes', on_delete=models.CASCADE)

    def __str__(self):
        return f' {self.user} хареса {self.post.title}'


class Notification(models.Model):
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    content = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey('store.Order', on_delete=models.CASCADE, blank=True, null=True)
    read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Notification for {self.recipient}: {self.content}"

    @classmethod
    def create_notification(cls, recipient, content, post=None, order=None):
        return cls.objects.create(recipient=recipient, content=content, post=post, order=order)

crafted_and_connected/social/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'price', 'delivery_time', 'category', 'subcategory', 'photos']

    category = forms.ChoiceField(choices=Post.CATEGORY_CHOICES, required=True)
    subcategory = forms.ChoiceField(choices=[], required=True)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        # Set the initial choices for category and subcategory
        self.fields['category'].choices = [('', 'Избери категория')] + list(Post.CATEGORY_CHOICES)
        self.fields['subcategory'].choices = [('', 'Избери подкатегория')]

        # Set labels for fields
        self.fields['category'].label = 'Категория'
        self.fields['subcategory'].label = 'Подкатегория'
        self.fields['title'].label = "Заглавие:"
        self.fields['description'].label = "Описание:"
        self.fields['price'].label = "Цена:"
        self.fields['delivery_time'].label = "Време за доставка(дни)"
        self.fields['photos'].label = "Качване на снимка:"

        # Set choices for subcategory based on the selected category or instance category
        if 'category' in self.data:
            category = self.data.get('category')
            self.fields['subcategory'].choices = ([('', 'Избери подкатегория')]
                                                  + list(Post.SUBCATEGORY_CHOICES.get(category, [])))
        elif self.instance.pk:
            category = self.instance.category
            self.fields['subcategory'].choices = ([('', 'Избери подкатегория')]
                                                  + list(Post.SUBCATEGORY_CHOICES.get(category, [])))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Добави коментар...'}, )
        }

crafted_and_connected/social/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Notification, Follow
from .forms import PostForm, CommentForm
from ..authentication.models import CustomUser
from django.urls import reverse


@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Notify followers about the new post
            followers = Follow.objects.filter(followed=request.user)
            for follower_relation in followers:
                follower = follower_relation.follower
                Notification.objects.create(
                    recipient=follower,
                    content=f"{request.user.first_name} {request.user.last_name} добави нова публикация '{post.title}'",
                    post=post
                )

            return redirect('profile')
    else:
        form = PostForm()
    return render(request, 'social/add_post.html', {'form': form})


def load_subcategories(request):
    category = request.GET.get('category')
    subcategories = Post.SUBCATEGORY_CHOICES.get(category, [])
    return JsonResponse([{'value': subcategory[0], 'display': subcategory[1]} for subcategory in subcategories],
                        safe=False)


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    is_liked = post.likes.filter(id=request.user.id).exists()
    show_all = request.GET.get('show_all', 'false') == 'true'
    comments = post.comments.all() if show_all else post.comments.all()[:4]
    is_following_post_user = Follow.objects.filter(follower=request.user, followed=post.user).exists()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('post_detail', post=post)
    else:
        form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'is_liked': is_liked,
        'form': form,
        'is_following_post_user': is_following_post_user,
        'show_all': show_all,
    }
    return render(request, 'social/post_detail.html', context)


@login_required
def follow_user(request, user_id):
    user_to_follow = get_object_or_404(CustomUser, id=user_id)
    follow, created = Follow.objects.get_or_create(follower=request.user, followed=user_to_follow)
    return redirect(reverse('user_profile', args=[user_id]))


@login_required
def unfollow_user(request, user_id):
    user_to_unfollow = get_object_or_404(CustomUser, id=user_id)
    Follow.objects.filter(follower=request.user, followed=user_to_unfollow).delete()
    return redirect(reverse('user_profile', args=[user_id]))


@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('post_detail', post_id=post_id)
    else:
        form = CommentForm()

    return redirect('post_detail', post_id=post_id)


@login_required
def notifications(request):
    user = request.user
    notifications = Notification.objects.filter(recipient=user).order_by('-timestamp')
    return render(request, 'social/notifications.html', {'notifications': notifications})


@login_required
def mark_notification_as_read(request, notification_id):
    notification = get_object_or_404(Notification, id=notification_id, recipient=request.user)
    notification.read = True
    notification.save()
    return redirect('notifications')


@login_required
def clear_notifications(request):
    user = request.user
    Notification.objects.filter(recipient=user).delete()
    return redirect('notifications')

templates/social/add_post.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
    <title>Crafted & Connected</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quando&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <div class="user-profile" style="max-width: 500px;%; min-width: 350px; height: 100%; margin: auto">
        <div><h1 style="padding: 20px 0;">Добавяне на нова публикация</h1></div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div style="min-width: 350px; max-width: 450px; margin: auto;" class="cart-info">
                
                {{ form.as_p }}
                
            </div>
            <button class="profile-buttons" type="submit" style="margin-top: 20px; width: 150px; font-size: 20px;">
                Добави публикация
            </button>
        </form>
    </div>


    <script>
        $(document).ready(function () {
            $('#id_category').change(function () {
                var category = $(this).val();
                var subcategorySelect = $('#id_subcategory');
                subcategorySelect.empty();  // Clear subcategory options

                if (category) {
                    $.ajax({
                        url: '{% url "load_subcategories" %}',
                        data: {
                            'category': category
                        },
                        success: function (data) {
                            subcategorySelect.append('<option value="">Избери подкатегория</option>');  // Add default option
                            $.each(data, function (index, subcategory) {
                                subcategorySelect.append('<option value="' + subcategory.value + '">' + subcategory.display + '</option>');  // Append subcategory options
                            });
                        }
                    });
                } else {
                    subcategorySelect.append('<option value="">Избери подкатегория</option>');  // Add default option
                }
            });
        });
    </script>
{% endblock %}

templates/social/notifications.html
{% extends 'base.html' %}

{% block title %}Notifications{% endblock %}

{% block page_content %}
    <body>
    <div class="container" style="background-color: wheat; height: auto; font-family: 'Montserrat', sans-serif;">
        <h1 style="text-align: center; font-family: 'Montserrat', sans-serif;, serif; font-optical-sizing: auto; font-weight: 400; font-style: normal; margin-bottom: 20px;">
            Известия</h1>
        <ul>
            {% for notification in notifications %}
                <div class="notification"
                     style="text-align: center; font-family: 'Roboto Slab', serif; font-optical-sizing: auto; font-weight: 400; font-size: 20px;"
                     class="{% if not notification.read %}unread{% endif %}">
                  
                    {% if notification.order %}
                        <li>Вашата поръчка №{{ notification.order_id }} е Приета.</li>
                        <a href="{% url 'order_details' notification.order.id %}">Виж поръчката</a>
                    {% else %}
                       <li>{{ notification.content }}</li>
                {% endif %}
                </div>

            {% endfor %}
            {% if notifications %}
                </ul>
                <div class="clear-notifications">
                    <form action="{% url 'clear_notifications' %}" method="post">
                        {% csrf_token %}
                        <div class="buttons" style="text-align: center">
                            <button class="profile-buttons" type="submit">Изчисти известията</button>
                        </div>

                    </form>
                </div>
            {% else %}
                <h3 style="text-align: center; margin: 20px;">Нямате известия</h3>
            {% endif %}
    </div>
    </body>
{% endblock %}

templates/social/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block page_content %}
    <title>Crafted & Connected</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quando&display=swap" rel="stylesheet">
    <title>{{ post.title }}</title>




    <div class="post">
        <div class="picture">
            <img src="{{ post.photos.url }}" alt="">
        </div>
        <div class="post-decription">
            <div class="grid-container">
                <div class="item1"><h3><a style="color: black;"
                                          href="{% url 'user_profile' post.user.id %}">{{ post.user.first_name }} {{ post.user.last_name }}</a>
                </h3></div>


                <div class="item11">
                    {% if not is_following_post_user %}
                        <form method="post" action="{% url 'follow_user' post.user.id %}">
                            {% csrf_token %}
                            <button class="profile-buttons" style="margin: 0; font-size: 18px;" type="submit">
                                Последвай
                            </button>
                        </form>
                    {% else %}
                        <form method="post" action="{% url 'unfollow_user' post.user.id %}">
                            {% csrf_token %}
                            <button class="profile-buttons" style="margin: 0; font-size: 18px;" type="submit">
                                Отпоследвай
                            </button>
                        </form>
                    {% endif %}
                </div>
                <div class="item3">
                    <div class="buttons">
                        <a class="after-login-buttons" style="margin-left: 30px;"
                           href="{% url 'chat_room' user_id=post.user.id %}?first_name={{ post.user.first_name }}&last_name={{ post.user.last_name }}">Съобщение</a>
                    </div>
                </div>
                
                <div class="item12">
                    <strong><b>{{ post.title }}</b></strong>
                </div>
                <div class="item13">
                    <strong><b> Срок на доставка: {{ post.delivery_time }} дни</b></strong>
                </div>

                <div class="item4">
                    {{ post.description }}
                </div>

                <div class="item5">
                    <div class="buttons" >
                        <a href=""  class="post-cat-and-subcat">{{ post.get_category_display }}</a>
                    </div>

                </div>
                <div class="buttons">
                    <a href="" class="post-cat-and-subcat">{{ post.get_subcategory_display }}</a>
                </div>
                <div class="item6">
                    Цена: {{ post.price }} лв
                </div>
                <div class="buttons">
                    <a href="{% url 'add_to_cart' post.id %}">Купи</a>
                </div>

            </div>
            <div class="comments">
                {% if comments %}
                    <h3 style="padding-left: 20px;">Коментари:</h3>
                {% endif %}
                <ul>
                    {% for comment in comments %}

                        <li style="font-size: 22px; padding-left: 10px;">
                            <div class="comment">
                                <img
                                        style="width: 50px;height: 50px; border-radius: 50px;"
                                        src="{{ comment.user.profile_picture.url }}"
                                        alt="">
                                <div class="comment-content">
                                    <div>
                                        <b>{{ comment.user.first_name }} {{ comment.user.last_name }} </b>{{ comment.created_at|timesince }}
                                        ago
                                    </div>
                                    <div>{{ comment.text }}</div>
                                </div>


                            </div>
                        </li>
                    {% empty %}
                        <p style="padding-left: 20px;">Няма коментари.</p>
                    {% endfor %}
                </ul>
                {% if not show_all and post.comments.count > 5 %}
                    <button id="load-more-comments" class="profile-buttons" style="font-size: 18px; margin: 0;">Зареди
                        всички коментари
                    </button>
                {% elif show_all %}
                    <button id="hide-comments" class="profile-buttons" style="font-size: 18px; margin: 0;">Скрий
                        коментарите
                    </button>
                {% endif %}

                <!-- Add a comment -->

            </div>

            <div class="comments-property">
                {% if post.comments.count > 0 %}
                    <div>
                        <h3 style="margin-left: 20px;">Коментари: {{ post.comments.count }}</h3>
                    </div>
                {% endif %}

                <div>
                    <div class="buttons">
                        <form method="POST" action="{% url 'like_post' post.id %}">
                            {% csrf_token %}
                            <button type="submit" class="like-button">
                                <i class="fas fa-heart" style="color: red; padding-left: 20px;">{% if is_liked %} Unlike {% else %}
                                    Like {% endif %}</i>
                            </button>
                            <i class="fas fa-heart" style="color: red;">{{ post.likes.count }} likes</i>
                        </form>

                    </div>
                </div>

            </div>
            <footer>
                <div class="add-comments" style="border-style: hidden;">
                    <div><img style="width: 60px; height: 60px; margin-left: 20px; border-radius: 50px;"
                              src="{{ request.user.profile_picture.url }}" alt=""></div>
                    <form class="comment-form" method="POST" action="{% url 'add_comment' post.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="profile-buttons" type="submit"
                                style="font-size: 18px; margin: 0;">
                            Добави коментар
                        </button>
                    </form>


                </div>
            </footer>
        </div>
    </div>
    <div>

    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var loadMoreBtn = document.getElementById('load-more-comments');
            var hideCommentsBtn = document.getElementById('hide-comments');

            if (loadMoreBtn) {
                loadMoreBtn.addEventListener('click', function () {
                    const urlParams = new URLSearchParams(window.location.search);
                    urlParams.set('show_all', 'true');
                    window.location.search = urlParams.toString();
                });
            }

            if (hideCommentsBtn) {
                hideCommentsBtn.addEventListener('click', function () {
                    const urlParams = new URLSearchParams(window.location.search);
                    urlParams.delete('show_all');
                    window.location.search = urlParams.toString();
                });
            }
        });
        document.getElementById('buy-link').addEventListener('click', function (event) {
            event.preventDefault();
            var postId = this.getAttribute('data-post-id');
            var url = "{% url 'add_to_cart' post_id=0 %}".replace('0', postId);
            fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': "{{ csrf_token }}",
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    // Handle success or error response
                    console.log(data);
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        });


    </script>
{% endblock %}